//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Users.WebApp.Applications.User.Features.UserList {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Users.WebApp.Applications.User.Features.UserList.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пригласить в кабинет.
        /// </summary>
        internal static string CreateUserButton_Label {
            get {
                return ResourceManager.GetString("CreateUserButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string CreateUserFormModal_CancelButton_Label {
            get {
                return ResourceManager.GetString("CreateUserFormModal_CancelButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление пользователя.
        /// </summary>
        internal static string CreateUserFormModal_Header {
            get {
                return ResourceManager.GetString("CreateUserFormModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string CreateUserFormModal_SubmitButton_Label {
            get {
                return ResourceManager.GetString("CreateUserFormModal_SubmitButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите валидный email.
        /// </summary>
        internal static string CreateUserFormModal_UserEmailInput_HelpText {
            get {
                return ResourceManager.GetString("CreateUserFormModal_UserEmailInput_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CreateUserFormModal_UserEmailInput_Label {
            get {
                return ResourceManager.GetString("CreateUserFormModal_UserEmailInput_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете одну или больше професий.
        /// </summary>
        internal static string CreateUserFormModal_UserProffesionslnput_HelpText {
            get {
                return ResourceManager.GetString("CreateUserFormModal_UserProffesionslnput_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Професии.
        /// </summary>
        internal static string CreateUserFormModal_UserProffesionslnput_Label {
            get {
                return ResourceManager.GetString("CreateUserFormModal_UserProffesionslnput_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string DeleteUserFormModal_CancelButton_Label {
            get {
                return ResourceManager.GetString("DeleteUserFormModal_CancelButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить?.
        /// </summary>
        internal static string DeleteUserFormModal_Description {
            get {
                return ResourceManager.GetString("DeleteUserFormModal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить пользователя?.
        /// </summary>
        internal static string DeleteUserFormModal_Header {
            get {
                return ResourceManager.GetString("DeleteUserFormModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string DeleteUserFormModal_SubmitButton_Label {
            get {
                return ResourceManager.GetString("DeleteUserFormModal_SubmitButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string EditUserFormModal_CancelButton_Label {
            get {
                return ResourceManager.GetString("EditUserFormModal_CancelButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование пользователя.
        /// </summary>
        internal static string EditUserFormModal_Header {
            get {
                return ResourceManager.GetString("EditUserFormModal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string EditUserFormModal_SubmitButton_Label {
            get {
                return ResourceManager.GetString("EditUserFormModal_SubmitButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите валидный email.
        /// </summary>
        internal static string EditUserFormModal_UserEmailInput_HelpText {
            get {
                return ResourceManager.GetString("EditUserFormModal_UserEmailInput_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EditUserFormModal_UserEmailInput_Label {
            get {
                return ResourceManager.GetString("EditUserFormModal_UserEmailInput_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        internal static string EmptyList_CreateUserButton {
            get {
                return ResourceManager.GetString("EmptyList_CreateUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавьте хотя бы одного пользователя..
        /// </summary>
        internal static string EmptyList_Description {
            get {
                return ResourceManager.GetString("EmptyList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список пуст.
        /// </summary>
        internal static string EmptyList_Header {
            get {
                return ResourceManager.GetString("EmptyList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи кабинета.
        /// </summary>
        internal static string EmptyList_PageTitle {
            get {
                return ResourceManager.GetString("EmptyList_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи кабинета.
        /// </summary>
        internal static string UserList_PageTitle {
            get {
                return ResourceManager.GetString("UserList_PageTitle", resourceCulture);
            }
        }
    }
}
